services:
  catalog-service:
    depends_on:
      - polar-postgres
      - config-service
    image: "catalog-service"
    container_name: "catalog-service"
    networks:
      - catalog-network
    ports:
      - 9001:9001
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8001
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_DATASOURCE_URL=jdbc:postgresql://polar-postgres:5432/polardb_catalog
      - SPRING_PROFILES_ACTIVE=testdata

  polar-postgres:
    image: "postgres:14.4"
    container_name: "polar-postgres"
    networks:
      - catalog-network
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test123
      - POSTGRES_DB=polardb_catalog

  config-service:
    image: "config-service"
    container_name: "config-service"
    networks:
      - catalog-network
    ports:
      - 8888:8888
      
networks:
  catalog-network:
    external: true